### ISSUE TITLE
Alert dialog show an error the second time you open it.

### ISSUE THREAD

**Issue by CarlosBM18** [mrzachnugent/react-native-reusables#24]
I noticed that the alert-dialog component shows an error the second time you open it.

`Error: You attempted to set the key width with the value 0 on an object that is meant to be immutable and has been frozen.`

https://github.com/mrzachnugent/react-native-reusables/assets/30117015/21518039-8c7e-4824-9456-a9a35e9dc2ae

**Comment by mrzachnugent** [comment]
Thanks for submitting an issue.

It should be fixed in the latest commit. In https://github.com/mrzachnugent/react-native-reusables/blob/main/components/ui/alert-dialog.tsx, copy the new `AlertDialogContent` component and let me know if that fixes it.

_Previously had the same issue with the `Card` component. It has to do with conditionally setting the shadow style. At the moment, I cannot get shadows to work with `NativeWind` but as soon as I can, I will remove setting the shadow with in a `style` and I will use the tailwind class instead._

**Comment by CarlosBM18** [comment]
It's still happening to me.

**Comment by CarlosBM18** [comment]
It's in a private repo :(

But, I'm just copying the base component and files as you can see in the video.

**Comment by CarlosBM18** [comment]
> Thanks for submitting an issue.
> 
> It should be fixed in the latest commit. In https://github.com/mrzachnugent/react-native-reusables/blob/main/components/ui/alert-dialog.tsx, copy the new `AlertDialogContent` component and let me know if that fixes it.
> 
> _Previously had the same issue with the `Card` component. It has to do with conditionally setting the shadow style. At the moment, I cannot get shadows to work with `NativeWind` but as soon as I can, I will remove setting the shadow with in a `style` and I will use the tailwind class instead._

@mrzachnugent I've seen that in the commit you only updated the `universal-ui` component. I'm using the base one, maybe that's why is not fixed.

**Comment by mrzachnugent** [comment]
Is this the component you are using?

```js
const AlertDialogContent = React.forwardRef<
  React.ElementRef<typeof Modal>,
  React.ComponentPropsWithoutRef<typeof Modal> & { overlayClass?: string }
>(
  (
    {
      className,
      children,
      animationType = 'fade',
      style: styleProp,
      overlayClass,
      ...props
    },
    ref
  ) => {
    const { colorScheme } = useColorScheme();
    const { visible, setVisible, closeOnOverlayPress } =
      useAlertDialogContext();
    const [style, setStyle] = React.useState<ViewStyle>(
      StyleSheet.flatten(styleProp)
    );

    React.useEffect(() => {
      setStyle(
        StyleSheet.flatten([
          colorScheme === 'dark' ? styles.shadowDark : styles.shadowLight,
          styleProp,
        ])
      );
    }, [styleProp, colorScheme]);

    return (
      <Modal
        ref={ref}
        animationType={animationType}
        transparent={true}
        visible={visible}
        onRequestClose={() => {
          setVisible((prev) => !prev);
        }}
        statusBarTranslucent
        {...props}
      >
        <Pressable
          onPressOut={
            closeOnOverlayPress
              ? () => {
                  setVisible(false);
                }
              : undefined
          }
          className={cn(
            'flex-1  justify-center items-center p-2',
            animationType !== 'slide' && 'bg-zinc-50/80 dark:bg-zinc-900/80',
            overlayClass
          )}
        >
          <Pressable
            style={style}
            className={cn(
              'bg-background rounded-2xl p-8 border border-border',
              className
            )}
            role={'alertdialog'}
          >
            {children}
          </Pressable>
        </Pressable>
      </Modal>
    );
  }
);

AlertDialogContent.displayName = 'AlertDialogContent';

```

**Comment by callum-gander** [comment]
Commenting here after this https://github.com/mrzachnugent/react-native-reusables/issues/19, as this issue is still open and I think they have a similar underlying cause. 

This is the exact same error as the one you helped me solve with the `Card` component, using these changes https://github.com/mrzachnugent/react-native-reusables/commit/cfba30e6b52ef72465668fe13ff1c4ab3d4fd602. However, this is persisting for me with `Select`. 

Taking a stab in the dark here, but given that there was clearly some sort of issue with Nativewind and React Native evaluating the styles below when it depended on `colorScheme`, resulting in you have to put it in a useEffect
```
style={
             colorScheme === 'dark' ? styles.shadowDark : styles.shadowLight
          }
```
Perhaps lines like 120 in `components/ui/select.tsx` are having a similar issue due to relying on `items` to be calculated?
```
      style={{ height: items.length * SELECT_ITEM_HEIGHT }}
```

I don't think providing a brand new minimally reproducible repo will help, if you just create a `Select` component with the repo I provided for that one, you get the same issue

**Comment by CarlosBM18** [comment]
> Is this the component you are using?

No @mrzachnugent , I'm using the one in the links on the root README. The README is pointing to these:

- https://github.com/mrzachnugent/react-native-reusables/blob/main/components/ui/alert-dialog.tsx
- https://github.com/mrzachnugent/react-native-reusables/blob/main/app/(main)/alert-dialog/index.tsx

I just copied the content of those files into my app.

**Comment by mrzachnugent** [comment]
I am unable to reproduce these errors on iOS or on Android. I am closing this issue because I am unable to fix a problem that I cannot reproduce. 

Please copy the latest version of the reusable,  and make sure your project's packages are up to date.

In the [latest commit](https://github.com/mrzachnugent/react-native-reusables/commit/56404668eb2a9dcf7431a1712250737de2e288de), I made some changes to the `Alert-Dialog` and the `Select` component.
@CarlosBM18  In the `Alert-Dialog`, I would get a warning on Android only so that's what I fixed.
@callum-gander In the `Select` component, I changed some styling for Androids and I memoized the content's style. 

If you are still getting this error with the latest version of the component, please create a new issue with a minimal reproduction repository so that I can see the same issue you are facing.

Thank you
